name: coverage
on: [workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.10.1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup project
        run: sudo python setup.py develop
      - name: Generate report
        run: |
          coverage run -m unittest
          coverage report --fail-under=80